package com.frauddetection.common.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

/**
 * Fraud Alert POJO representing a detected fraudulent or suspicious transaction.
 * 
 * Generated by the Flink processing pipeline when a transaction triggers
 * one or more fraud detection rules.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class FraudAlert implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier for this alert.
     */
    private String alertId;

    /**
     * Reference to the triggering transaction.
     */
    private String transactionId;

    /**
     * Customer/account identifier.
     */
    private String customerId;

    /**
     * Severity level of the alert.
     */
    private AlertSeverity severity;

    /**
     * Composite risk score (0.0 to 1.0).
     */
    private Double riskScore;

    /**
     * List of rules that were triggered.
     */
    private List<TriggeredRule> triggeredRules;

    /**
     * Transaction amount that triggered the alert.
     */
    private BigDecimal transactionAmount;

    /**
     * Currency of the transaction.
     */
    private String currency;

    /**
     * Merchant where the transaction occurred.
     */
    private String merchantName;

    /**
     * Location of the suspicious transaction.
     */
    private Location location;

    /**
     * Recommended action for this alert.
     */
    private RecommendedAction recommendedAction;

    /**
     * Timestamp when the alert was generated.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
    private Instant alertTime;

    /**
     * Original transaction event time.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
    private Instant transactionTime;

    /**
     * Processing latency in milliseconds (alertTime - transactionTime).
     */
    private Long processingLatencyMs;

    /**
     * Current status of the alert.
     */
    private AlertStatus status;

    /**
     * Analyst assigned to investigate (if any).
     */
    private String assignedAnalyst;

    /**
     * Notes or comments from investigation.
     */
    private String investigationNotes;

    /**
     * Calculates and sets the processing latency.
     */
    public void calculateProcessingLatency() {
        if (alertTime != null && transactionTime != null) {
            this.processingLatencyMs = alertTime.toEpochMilli() - transactionTime.toEpochMilli();
        }
    }

    /**
     * Returns a human-readable summary of the alert.
     */
    public String getSummary() {
        return String.format("[%s] %s alert for customer %s: $%.2f %s at %s (score: %.2f)",
                severity,
                recommendedAction,
                customerId,
                transactionAmount,
                currency,
                merchantName,
                riskScore);
    }

    @Override
    public String toString() {
        return getSummary();
    }
}


